"""create all tables

Revision ID: d141c201bbb2
Revises: 
Create Date: 2026-10-09 13:51:54.123866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd141c201bbb2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

BADGES = [
    {'code': 'century', 'name': 'Century', 'description': 'Solve 100 problems.'},
    {'code': 'double_century', 'name': 'Double Century', 'description': 'Solve 200 problems.'},
    {'code': 'full_circle', 'name': 'Full circle', 'description': 'Revise every problem in your line at least once.'},
    {'code': 'builder', 'name': 'Builder', 'description': 'Solve your first design problem.'},
    {'code': 'explorer', 'name': 'Explorer', 'description': 'Solve your first Graphs problem.'},
    {'code': 'on_fire', 'name': 'On fire', 'description': 'Keep a 7-day streak.'},
    {'code': 'unstoppable', 'name': 'Unstoppable', 'description': 'Keep a 30-day streak.'},
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('daily_bytes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('topic', sa.String(length=50), nullable=True),
    sa.CheckConstraint("type IN ('code', 'fact')", name='ck_daily_byte_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problem_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('pattern', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.String(length=10), nullable=False),
    sa.Column('companies', sa.Text(), nullable=True),
    sa.Column('sources', sa.Text(), nullable=True),
    sa.Column('is_design', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_custom', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('real_life', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_bank_slug'), 'problem_bank', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('round_days', sa.Integer(), server_default='30', nullable=False),
    sa.Column('max_daily', sa.Integer(), server_default='10', nullable=False),
    sa.Column('new_per_day', sa.Integer(), server_default='2', nullable=False),
    sa.Column('target_company', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_badges',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_on', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'badge_id')
    )
    op.create_table('user_problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='new', nullable=False),
    sa.Column('solved_on', sa.Date(), nullable=False),
    sa.Column('last_revised_on', sa.Date(), nullable=True),
    sa.Column('times_revised', sa.Integer(), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('new', 'in_queue', 'retired')", name='ck_user_problem_status'),
    sa.ForeignKeyConstraint(['problem_id'], ['problem_bank.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'problem_id', name='uq_user_problem')
    )
    op.create_index(op.f('ix_user_problems_user_id'), 'user_problems', ['user_id'], unique=False)
    op.create_table('user_stats',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_xp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('current_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('best_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_streak_day', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_problem_id', sa.Integer(), nullable=False),
    sa.Column('revised_on', sa.Date(), nullable=False),
    sa.Column('section', sa.String(length=10), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.CheckConstraint("section IN ('warmup', 'loop', 'new')", name='ck_revision_section'),
    sa.ForeignKeyConstraint(['user_problem_id'], ['user_problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revisions_user_problem_id'), 'revisions', ['user_problem_id'], unique=False)
    # ### end Alembic commands ###

    # Seed the badges (PLAN.md section 6.4). The rules live in services/badges.py.
    badges_table = sa.table(
        'badges',
        sa.column('code', sa.String),
        sa.column('name', sa.String),
        sa.column('description', sa.Text),
    )
    op.bulk_insert(badges_table, BADGES)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revisions_user_problem_id'), table_name='revisions')
    op.drop_table('revisions')
    op.drop_table('user_stats')
    op.drop_index(op.f('ix_user_problems_user_id'), table_name='user_problems')
    op.drop_table('user_problems')
    op.drop_table('user_badges')
    op.drop_table('settings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_problem_bank_slug'), table_name='problem_bank')
    op.drop_table('problem_bank')
    op.drop_table('daily_bytes')
    op.drop_table('badges')
    # ### end Alembic commands ###
